services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    depends_on:
      - app
    environment:
      TZ: Asia/Taipei
    env_file:
      - .env
    command: tunnel --no-autoupdate run --token ${CLOUDFLARE_TUNNEL_TOKEN}
    restart: unless-stopped
